version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: RelWithDebInfo
clone_folder: c:\local\source
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- cmd: >-
    set PREBUILT_CEF_VERSION=3.3440.1805.gbe070f9

    set PREBUILT_OBS_STUDIO_DIST_URL_64=https://cdn-fastly.obsproject.com/downloads/OBS-Studio-23.2.1-Full-x64.zip

    set PREBUILT_OBS_STUDIO_DIST_URL_32=https://cdn-fastly.obsproject.com/downloads/OBS-Studio-23.2.1-Full-x86.zip
  
    cinst -y git

    cinst -y cmake

    cinst -y curl


    if not exist c:\local md c:\local


    git clone --recursive https://github.com/jp9000/obs-studio.git c:\local\obs-studio

    cd /d c:\local\obs-studio

    git checkout 23.2.1

    git submodule update --init --recursive

    rd /s /q c:\local\obs-studio\plugins\obs-browser

    cd /d c:\local


    xcopy c:\local\source\*.* c:\local\obs-studio\plugins\obs-browser /S /E /I /Y


    echo add_subdirectory(obs-browser) >c:\local\obs-studio\plugins\CMakeLists.txt


    if exist BugSplat.zip (curl -kL -o BugSplat.zip https://cdn.streamelements.com/obs/dist/third-party/bugsplat/BugSplatNative.zip -f --retry 5 -z BugSplat.zip) else (curl -kL -o BugSplat.zip https://cdn.streamelements.com/obs/dist/third-party/bugsplat/BugSplatNative.zip -f --retry 5 -C -) 2>&1 >nul:


    if exist cef64.zip (curl -kL -o cef64.zip https://cdn-fastly.obsproject.com/downloads/cef_binary_%PREBUILT_CEF_VERSION%_windows64.zip -f --retry 5 -z cef64.zip) else (curl -kL -o cef64.zip https://cdn-fastly.obsproject.com/downloads/cef_binary_%PREBUILT_CEF_VERSION%_windows64.zip -f --retry 5 -C -) 2>&1 >nul:

    if exist cef32.zip (curl -kL -o cef32.zip https://cdn-fastly.obsproject.com/downloads/cef_binary_%PREBUILT_CEF_VERSION%_windows32.zip -f --retry 5 -z cef32.zip) else (curl -kL -o cef32.zip https://cdn-fastly.obsproject.com/downloads/cef_binary_%PREBUILT_CEF_VERSION%_windows32.zip -f --retry 5 -C -) 2>&1 >nul:


    if exist dependencies2017.zip (curl -kLO https://obsproject.com/downloads/dependencies2017.zip -f --retry 5 -z dependencies2017.zip) else (curl -kLO https://obsproject.com/downloads/dependencies2017.zip -f --retry 5 -C -) 2>&1 >nul:


    if exist vlc.zip (curl -kLO https://obsproject.com/downloads/vlc.zip -f --retry 5 -z vlc.zip) else (curl -kLO https://obsproject.com/downloads/vlc.zip -f --retry 5 -C -) 2>&1 >nul:


    if exist obs-studio-dist-32.zip (curl -kL -o obs-studio-dist.zip %PREBUILT_OBS_STUDIO_DIST_URL_32% -f --retry 5 -z obs-studio-dist-32.zip) else (curl -kL -o obs-studio-dist-32.zip %PREBUILT_OBS_STUDIO_DIST_URL_32% -f --retry 5 -C -) 2>&1 >nul:

    if exist obs-studio-dist-64.zip (curl -kL -o obs-studio-dist.zip %PREBUILT_OBS_STUDIO_DIST_URL_64% -f --retry 5 -z obs-studio-dist-64.zip) else (curl -kL -o obs-studio-dist-64.zip %PREBUILT_OBS_STUDIO_DIST_URL_64% -f --retry 5 -C -) 2>&1 >nul:

    7z x -y dependencies2017.zip -odependencies2017

    7z x -y vlc.zip -ovlc


    7z x -y c:\local\BugSplat.zip

    7z x -y c:\local\cef32.zip

    7z x -y c:\local\cef64.zip

    7z x -y c:\local\obs-studio-dist-32.zip -oobs-studio-dist

    7z x -y c:\local\obs-studio-dist-64.zip -oobs-studio-dist

    set DepsPath32=c:\local\dependencies2017\win32

    set DepsPath64=c:\local\dependencies2017\win64

    set VLCPath=c:\local\vlc

    set QTDIR32=C:\Qt\5.10.1\msvc2015

    set QTDIR64=C:\Qt\5.10.1\msvc2017_64

    set build_config=RelWithDebInfo
cache:
- c:\local\BugSplat.zip
- c:\local\dependencies2017.zip
- c:\local\vlc.zip
- c:\local\obs-studio-dist-32.zip
- c:\local\obs-studio-dist-64.zip
- c:\local\cef64.zip
- c:\local\cef32.zip
build_script:
- cmd: >-
    echo ("#define STREAMELEMENTS_PLUGIN_VERSION " + (Get-Date).ToUniversalTime().ToString("yyyyMMdd") + "${Env:APPVEYOR_BUILD_NUMBER}".PadLeft(6, '0')) >c:\local\generate_version.ps1

    echo ("set STREAMELEMENTS_PLUGIN_VERSION=" + (Get-Date).ToUniversalTime().ToString("y.M.d") + "." + "${Env:APPVEYOR_BUILD_NUMBER}".PadLeft(1, '0')) >c:\local\generate_version_cmd.ps1

    powershell -File c:\local\generate_version.ps1 >c:\local\obs-studio\plugins\obs-browser\streamelements\Version.generated.hpp

    powershell -File c:\local\generate_version_cmd.ps1 >c:\local\generate_version_cmd.bat

    c:\local\generate_version_cmd.bat

    echo %STREAMELEMENTS_PLUGIN_VERSION%

    cd /d c:\local\obs-studio

    mkdir build build32 build64


    echo.===================== PATCH =====================

    copy /y c:\local\obs-studio\plugins\obs-browser\streamelements\patch\qt\qalgorithms.h %QTDIR32%\include\qtcore\qalgorithms.h

    echo.===================== BUILD 64 BIT - OBS-STUDIO =====================

    cd /d c:\local\obs-studio\build64

    "C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 2017 Win64" -DEXPERIMENTAL_SHARED_TEXTURE_SUPPORT_ENABLED=true -DBROWSER_PANEL_SUPPORT_ENABLED=true -DENABLE_SCRIPTING=false -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=true -DCEF_ROOT_DIR=c:\local\cef_binary_%PREBUILT_CEF_VERSION%_windows64  -DBUGSPLAT_ROOT_DIR=c:\local\BugSplat ..

    cd /d c:\local\obs-studio\build64

    msbuild obs-studio.sln /p:Configuration=%build_config% /t:Build

    echo.Upload 64bit PDBs to BugSplat in case this is a commit to master branch.

    if "%APPVEYOR_PULL_REQUEST_HEAD_COMMIT%"=="" c:\local\BugSplat\bin\SendPdbs.exe /u "%BUGSPLAT_USERNAME%" /p "%BUGSPLAT_PASSWORD%" /a obs-browser /v "%STREAMELEMENTS_PLUGIN_VERSION%" /b OBS_Live /d "c:\local\obs-studio\build64\rundir\%build_config%\obs-plugins\64bit" /f obs-browser.pdb;cef-bootstrap.pdb




    echo.===================== BUILD 32 BIT - OBS-STUDIO =====================

    cd /d c:\local\obs-studio\build32

    "C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 2017" -DEXPERIMENTAL_SHARED_TEXTURE_SUPPORT_ENABLED=true -DBROWSER_PANEL_SUPPORT_ENABLED=true -DENABLE_SCRIPTING=false -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=true -DCEF_ROOT_DIR=c:\local\cef_binary_%PREBUILT_CEF_VERSION%_windows32 -DBUGSPLAT_ROOT_DIR=c:\local\BugSplat ..

    cd /d c:\local\obs-studio\build32

    msbuild obs-studio.sln /p:Configuration=%build_config% /t:Build

    echo.Upload 32bit PDBs to BugSplat in case this is a commit to master branch.

    if "%APPVEYOR_PULL_REQUEST_HEAD_COMMIT%"=="" c:\local\BugSplat\bin\SendPdbs.exe /u "%BUGSPLAT_USERNAME%" /p "%BUGSPLAT_PASSWORD%" /a obs-browser /v "%STREAMELEMENTS_PLUGIN_VERSION%" /b OBS_Live /d "c:\local\obs-studio\build32\rundir\%build_config%\obs-plugins\32bit" /f obs-browser.pdb;cef-bootstrap.pdb




    echo.===================== COPY CEF 64 BIT BINARIES FROM OBS-STUDIO-DIST =====================

    cd /d c:\local\obs-studio\build64\rundir\%build_config%\obs-plugins\64bit

    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\locales\*.* .\locales

    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\cef.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\cef_100_percent.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\cef_200_percent.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\cef_extensions.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\devtools_resources.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\icudtl.dat .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\chrome_elf.dll .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\libcef.dll .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\libEGL.dll .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\libGLESv2.dll .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\natives_blob.bin .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\snapshot_blob.bin .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\64bit\v8_context_snapshot.bin .




    
    
    echo.===================== COPY CEF 32 BIT BINARIES FROM OBS-STUDIO-DIST =====================

    cd /d c:\local\obs-studio\build32\rundir\%build_config%\obs-plugins\32bit

    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\locales\*.* .\locales
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\cef.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\cef_100_percent.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\cef_200_percent.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\cef_extensions.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\devtools_resources.pak .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\icudtl.dat .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\chrome_elf.dll .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\libcef.dll .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\libEGL.dll .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\libGLESv2.dll .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\natives_blob.bin .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\snapshot_blob.bin .
    
    copy /Y /B /Z c:\local\obs-studio-dist\obs-plugins\32bit\v8_context_snapshot.bin .






    echo.===================== PACK ARTIFACTS =====================

    cd /d c:\local\source

    del /f /q c:\local\source\appveyor.yml    

    7z a c:\local\obs-browser-master.zip .

    move /Y c:\local\obs-browser-master.zip c:\local\source\obs-browser-master.zip



    cd /d c:\local\obs-studio\build64\rundir\%build_config%

    7z a c:\local\source\build64.zip .



    cd /d c:\local\obs-studio\build32\rundir\%build_config%

    7z a c:\local\source\build32.zip .



    copy /Y c:\local\obs-studio\plugins\obs-browser\streamelements\Version.generated.hpp c:\local\source\streamelements\Version.generated.hpp
test: off
artifacts:
- path: build32.zip
  name: build32
- path: build64.zip
  name: build64
- path: streamelements\Version.generated.hpp
  name: version.generated.hpp
- path: obs-browser-master.zip
  name: obs-browser-master
deploy:
- provider: S3
  access_key_id: AKIAJESHQW2DGHPN57KQ
  secret_access_key:
    secure: lhOyqT4/E0Oqv8BOQR81rx/SweOIbDELTYW7iJTqRz5shmkZ8eXMCgFzcIuXyvpB
  bucket: obs-builds
  folder: obs-browser/latest/windows
  artifact: build32,build64,obs-browser-master,version.generated.hpp
  max_error_retry: 5
  on:
    branch: master
on_success:
- cmd: set
