version: 2.1
jobs:
  build:
    macos:
      xcode: 12.1.0
    steps:
      - checkout
      - run:
          name: Build
          command: |
            printf "Building STREAMELEMENTS_PLUGIN_VERSION %s\n" `date +%Y.%m.%d.${CIRCLE_BUILD_NUM}`

            export TERM=xterm-256color

            brew install awscli
            
            cd ..

            git clone --recursive https://github.com/obsproject/obs-studio.git

            rm -rf obs-studio/plugins/obs-browser

            mv project obs-studio/plugins/obs-browser

            cd obs-studio

            ls -l plugins
            ls -l plugins/obs-browser
            ls -l plugins/obs-browser/streamelements

            printf "#define STREAMELEMENTS_PLUGIN_VERSION %s%06dL\n" `date +%Y%m%d` ${CIRCLE_BUILD_NUM} >plugins/obs-browser/streamelements/Version.generated.hpp

            ls -l plugins/obs-browser/streamelements

            cat plugins/obs-browser/streamelements/Version.generated.hpp

            ls -l plugins/obs-browser/streamelements

            ./CI/full-build-macos.sh -b

            echo "Branch: ${CIRCLE_BRANCH}"

            if [ ${CIRCLE_BRANCH} = master ]; then
              aws s3 cp "build/OBS.app/Contents/PlugIns/obs-browser.so" "s3://obs-builds/obs-browser/latest/macos/obs-browser.so";
              aws s3 sync "build/OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework" "s3://obs-builds/obs-browser/latest/macos/Chromium Embedded Framework.framework";
            else
              exit 0;
            fi;
