version: 2.1
jobs:
  build:
    macos:
      xcode: 12.1.0
    steps:
      - checkout
      - run:
          name: Build
          command: |
            export TERM=xterm-256color

            brew install awscli
            
            cd ..

            git clone --recursive https://github.com/obsproject/obs-studio.git

            mv project obs-studio/plugins/obs-browser

            cd obs-studio

            ./CI/full-build-macos.sh -b

            echo "Branch: ${CIRCLE_BRANCH}"

            if [ ${CIRCLE_BRANCH} = macos_build ]; then
              aws s3 cp "build/OBS.app/Contents/PlugIns/obs-browser.so" "s3://obs-builds/obs-browser/latest/macos/obs-browser.so";
              aws s3 sync "build/OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework" "s3://obs-builds/obs-browser/latest/macos/Chromium Embedded Framework.framework" --dryrun;
            else
              exit 0;
            fi;
